carte/urls.py
from django.conf.urls import url
from . import views


app_name = "carte"

urlpatterns = [
    # carte/
    url(r'^$', views.index, name="index"),
]

cv/urls.py
from django.conf.urls import url
from . import views


app_name = "cv"

urlpatterns = [
    # cv/
    url(r'^$', views.index, name="index"),
]

home/urls.py
from django.conf.urls import url
from . import views


app_name = "home"

urlpatterns = [
    # /home/
    url(r'^$', views.index, name="index"),
]

relativity/urls.py
from django.conf.urls import url
from . import views


app_name = "relativity"

urlpatterns = [
    # relativity/
    url(r'^$', views.index, name="index"),
]

smokysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', include("home.urls", namespace="home")),
    url(r'^cv/', include("cv.urls", namespace="cv")),
    url(r'^carte/', include("carte.urls", namespace="carte")),
    url(r'^relativity/', include("relativity.urls", namespace="relativity")),
]

carte/models.py
from django.db import models

# Create your models here.

relativity/forms.py
from django import forms


class SpeedForm(forms.Form):
    distance = forms.IntegerField(min_value=1, help_text="The distance travelled")
    duration = forms.IntegerField(min_value=1, help_text="The duration taken to travel the distance")

carte/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'carte/index.html')

cv/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, 'cv/index.html')

home/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html')

relativity/views.py
from django.shortcuts import render
from .forms import SpeedForm


def speed(distance, duration):
    """
    Calculates speed
    :param distance:
    :param duration:
    :return speed:
    """
    results = distance / duration
    return results


def index(request):
    """
    Home page of the Relativity app
    :param request:
    :return home page with values if available:
    """
    form = SpeedForm(request.POST or None)

    if form.is_valid():
        speed_result = speed(
            distance=int(form.cleaned_data["distance"]),
            duration=int(form.cleaned_data["duration"]))
        return render(
            request,
            'relativity/index.html',
            context={
                "speed": speed_result,
                "distance": form.cleaned_data["distance"],
                "duration": form.cleaned_data["duration"]})
    return render(request, 'relativity/index.html')

templates/base.html
<!DOCTYPE html>

<!-- Author: Simon Lachaîne -->

<html lang="en">
<head>

    {% block meta %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %}Simon Lachaîne{% endblock %}</title>

        {% load staticfiles %}

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- Custom styling -->
        <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'home/sidebar.css' %}"/>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans|Ubuntu" rel="stylesheet">
    {% endblock %}
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top navbar-static-top">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">

            <!-- Collapse button -->
{#            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#TopNavBar">#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#                <span class="icon-bar"></span>#}
{#            </button>#}

            <ul class="nav nav-pills navbar-toggle">
                <li><a data-toggle="collapse" data-target="#TopNavBar">
                    <span class="glyphicon glyphicon-menu-hamburger"></span></a>
                </li>
            </ul>


            <!-- Header buttons -->
            <ul class="nav nav-pills">

                <li ><a href="#" id="menu-toggle">
                    <span class="glyphicon glyphicon-menu-hamburger"></span></a></li>

                <li><a href="{% url 'home:index' %}">
                        <span class="glyphicon glyphicon-home" aria-hidden="true"></span></a>
                </li>
            </ul>
        </div>

        <!-- Navbar Items -->
        <div class="collapse navbar-collapse" id="TopNavBar">

            <div class="nav navbar-nav navbar-left">

                <ul class="nav nav-pills">
                    <li><a href="#">News</a></li>
                    <li><a href="#">Programs</a></li>
                    <li><a href="#">Programming Recipes</a></li>
                    <li><a href="#">References</a></li>
                </ul>

            </div>

            <div class="nav navbar-nav navbar-right">

                <ul class="nav nav-pills">
                    <li><a href="#"><span class="glyphicon glyphicon-info-sign"></span></a></li>
                    <li><a href="#"><span class="glyphicon glyphicon-envelope"></span></a></li>
                </ul>

            </div>

        </div>
    </div>
</nav>

<div id="wrapper">

    <!--Sidebar-->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="dropdown">
                <li><a data-toggle="collapse" href="#collapse-news"><strong>Latest News</strong>
                <span class="caret"></span></a>
                </li>
                <li id="collapse-news" class="collapse">
                    <ul class="sidebar-nav">
                        <li><a href="#">News 1</a></li>
                        <li><a href="#">News 2</a></li>
                        <li><a href="#">News 3</a></li>
                    </ul>
                </li>
            </li>
            <li class="dropdown">
                <li><a data-toggle="collapse" href="#collapse-programs"><strong>Programs</strong>
                <span class="caret"></span></a>
                </li>
                <li id="collapse-programs" class="collapse">
                    <ul class="sidebar-nav">
                        <li><a href="#">Lorentz Calculator</a></li>
                        <li><a href="#">Blackjack</a></li>
                        <li><a href="#">President</a></li>
                    </ul>
                </li>
            </li>
            <li class="dropdown">
                <li><a data-toggle="collapse" href="#collapse-recipes"><strong>Programming Recipes</strong>
                <span class="caret"></span></a>
                </li>
                <li id="collapse-recipes" class="collapse">
                    <ul class="sidebar-nav">
                        <li><a href="#">Python</a></li>
                        <li><a href="#">Javascript</a></li>
                        <li><a href="#">Bootstrap</a></li>
                    </ul>
                </li>
            </li>
            <li><a href="#"><strong>References</strong></a></li>
            <li><a href="#"><strong>About</strong></a></li>
            <li><a href="#"><strong>Contact</strong></a></li>
        </ul>
    </div>

    <!--Page Content-->
    <div id="page-content-wrapper">

        {% block body %}

        {% endblock %}

    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script>
    $("#menu-toggle").click( function (e) {
       e.preventDefault();
       $("#wrapper").toggleClass("menuToggle");
    });
</script>

</body>
</html>

templates/carte/index.html
<!DOCTYPE html>
<!-- Author: Simon Lachaîne -->
<html lang="fr">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Joyeux anniversaire!</title>

    {% load staticfiles %}

    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'carte/style.css' %}">

</head>

<body>

    <div class="flex-container">
        <header>
            <h1 class="well well-lg">Joyeux anniversaire!</h1>
        </header>

        <article>
            <p class="well">Chère Maud,</p>

            <p class="well">je sais que tu aimes les chats,</p>

            <p class="well">alors voici de mignons chattons!</p>
        </article>

        <audio>
            <source src="{% static 'carte/audio/cat.mp3' %}" type="audio/mpeg">
            Your browser does not support the audio element.
        </audio>

    </div>

    <!-- jQuery CDN -->
    <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>

    <!-- Javascript source -->
    <script type="text/javascript" src="{% static 'carte/js/anniversaire.js' %}"></script>

</body>

</html>

templates/cv/index.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <!-- Author: Simon Lachaîne -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'cv/style.css' %}"/>
    <title>Simon Lachaîne - CV</title>
</head>

<body>

<!-- Flexbox container -->
<div class="flex-container">

    <!-- Header -->
    <header>
        <h1>Simon Lachaîne</h1>
        <h3>Programmeur Python</h3>
    </header>

    <div class="flex-container main">

        <!-- Photo and LinkedIn Link -->
        <aside>
            <a href="{% static 'cv/images/simon.jpg' %}">
                <img src="{% static 'cv/images/simon_mini.jpg' %}" alt="Photo de Simon Lachaîne" title="Simon Lachaîne" id="photo"/>
            </a>

            <address>
                <script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
                <script type="IN/MemberProfile" data-id="https://www.linkedin.com/in/slachaine" data-format="hover" data-related="false" data-text="Contact"></script>
            </address>
        </aside>

        <div class="flex-container inner">
            <article>
                <!-- Section Expérience -->
                <section>
                    <h2>Expérience</h2>
                    <ul>
                        <li><strong>Programmeur de métadonnées</strong> - Technicolor Services Créatifs (2015-présent)
                            <ul class="sublist">
                                <li>Développement d'<em>outils logiciels</em> pour accélérer la production et réduire le risque d'erreur</li>
                                <li>Préparation des métadonnées en format <em>XML</em> selon les spécifications des différentes plateformes</li>
                            </ul>
                        </li>
                        <li><strong>Gestionnaire de données</strong> - Technicolor Services Créatifs (2014-2015)</li>
                        <li><strong>Technicien contrôle qualité DVD/BD</strong> - Technicolor Services Créatifs (2010-2014)</li>
                    </ul>
                </section>

                <!-- Section Compétences -->
                <section>
                    <h2>Compétences</h2>
                    <ul>
                        <li><strong>Python</strong>: Connaissance approfondie
                            <ul>
                                <li>Développement de plusieurs applications desktop avec <em>PyQt</em></li>
                                <li>Développement de quelques projets web avec <em>Django</em></li>
                                <li>Développement d'un projet d'analyse de données avec <em>Pandas</em> et <em>Matplotlib</em></li>
                            </ul>
                        </li>
                        <li><strong>HTML5</strong> et <strong>CSS3</strong>: Connaissance fonctionnelle</li>
                        <li><strong>Javascript</strong>, <strong>jQuery</strong> et <strong>PHP</strong>: Connaissances de base</li>
                    </ul>
                </section>

                <!-- Section Formation -->
                <section>
                    <h2>Formation</h2>
                    <ul>
                        <li><a href="https://www.coursera.org" target="_blank">Coursera</a>: An Introduction to Interactive Programming in Python</li>
                        <li><a href="https://www.pluralsight.com" target="_blank">Pluralsight</a>: Python Desktop Application Development</li>
                        <li><a href="https://openclassrooms.com" target="_blank">OpenClassrooms</a>: Apprenez à créer votre site web avec HTML5 et CSS3</li>
                        <li><a href="https://openclassrooms.com" target="_blank">OpenClassrooms</a>: Découvrez la programmation orientée objet avec Python</li>
                        <li><a href="https://openclassrooms.com" target="_blank">OpenClassrooms</a>: Introduction à jQuery</li>
                        <li><a href="https://www.udemy.com/" target="_blank">Udemy</a>: Python and Django Full Stack Web Developer Bootcamp (en cours)</li>
                    </ul>
                </section>
            </article>

            <!-- Footer -->
            <footer>
                <h4>Page créée en 2017 par Simon Lachaîne</h4>
            </footer>

        </div>
    </div>
</div>

</body>
</html>

templates/home/index.html
{% extends "base.html" %}

{% block body %}

    {% load staticfiles %}

    <div class="container-fluid">

        <div class="text-center">
            <br/><h1>Welcome to my site.</h1><br/>

            <img src="{% static 'home/images/Simon.jpg' %}" class="img-responsive center-block img-circle" width="200" height="200">

            <h3>I'm Simon Lachaîne.</h3><br/>
        </div>

        <div class="text-center">
            <p>This site will be used to practice my coding skills, as well as to display a few programs and some programming recipes.</p>

            <p>It is my hope that this will remain an ever-evolving work-in-progress that follows my learning.</p>

            <p>Hope you enjoy what little there is to see now and thanks for visiting!</p>
        </div><br/><br/>

        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <div class="well" style="background: skyblue"><h4><strong>Site Components</strong></h4>

                    <a href="https://www.python.org/">
                        <div class="well" id="well-link">
                        <h4>Python 3</h4>
                        Widely used, Python is a high-level, general-purpose, interpreted, dynamic programming language with emphasis on quick development and code readability.
                    </div></a>
                    <a href="https://www.djangoproject.com/start/overview/">
                        <div class="well" id="well-link">
                        <h4>Django</h4>
                        Originally developed for the newsroom environment, Django is a web framework for Python providing fast development and easy implementation of security features.
                    </div></a>
                    <a href="http://getbootstrap.com/">
                        <div class="well" id="well-link">
                        <h4>Bootstrap</h4>
                            Bootstrap is the most popular HTML, CSS, and JS framework for developing responsive, mobile first projects on the web.
                    </div></a>
                    <a href="https://sqlite.org/">
                        <div class="well" id="well-link">
                        <h4>SqLite</h4>
                            SQLite is a self-contained, high-reliability, embedded, full-featured, public-domain, SQL database engine.
                    </div></a>
                    <a href="https://github.com/SimonTheChain/smokysite">
                        <div class="well" id="well-link">
                        <h4>GitHub</h4>
                            Code available on GitHub.
                    </div></a>
                </div>
            </div>
            <div class="col-md-2"></div>
        </div>

    </div>

{% endblock %}

templates/relativity/index.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <!-- Author: Simon Lachaîne -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'relativity/style.css' %}"/>
    <title>Simon Lachaîne - Special Relativity</title>
</head>

{% block body %}

    <h1>Special Relativity</h1>
    <h2>A Math-Based Introduction</h2>

    <h3>Speed</h3>
    <form action="{% url "relativity:index" %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

        <p>The
            <input type="submit" class="btn" name="speed_btn" value="Measure">
            of
            <label for="distance">Distance</label>
            <input id="distance" type="number" name="distance" value="{% if distance %}{{ distance }}{% endif %}">
            divided by
            <label for="duration">Duration</label>
            <input id="duration" type="number" name="duration" value="{% if duration %}{{ duration }}{% endif %}">
            (Space over Time):
            {% if speed %}
                {{ speed }}
            {% endif %}
        </p>
    </form>
    <h4>Speed is always relative to something.</h4>
    <p>If you are in <strong>Constant Velocity Motion</strong>,
        you are totally justified to claim that you are still,
        and that it is the world around you that moves by you.</p>
    <h4>Speed is additive and subtractive.</h4>
    <p>If you run away from an object coming toward you, it'll approach less quickly.</p>

    <h3>The Speed of Light</h3>
    <form action="{% url "relativity:index" %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}

        <p>The
            <input type="submit" class="btn" name="speed_btn" value="Measure">
            of
            <label for="distance">Distance</label>
            <input id="distance" type="number" name="distance" value="{% if distance %}{{ distance }}{% endif %}">
            divided by
            <label for="duration">Duration</label>
            <input id="duration" type="number" name="duration" value="{% if duration %}{{ duration }}{% endif %}">
            (Space over Time):
            {% if speed %}
                {{ speed }}
            {% endif %}
        </p>
    </form>
    <h4>The speed of light is constant.</h4>
    <p>The speed of light (c) is 299,792,458 meters per second.</p>
    <h4>Speed is additive and subtractive.</h4>
    <p>If you run away from an object coming toward you, it'll approach less quickly.</p>

{% endblock %}